# -*- coding: utf-8 -*-
"""b(e^ax).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18zGshA-RFmTShrdjSrOV4wAa_EdFrrU-
"""

import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(-2, 2, 400)
a_values = [-2, -1, 0, 1, 2]
b_values = [0.5, 1, 2]


fig, axes = plt.subplots(1, len(b_values), figsize=(18, 5))

for i, b in enumerate(b_values):
    for a in a_values:
        y = b * np.exp(a * x)
        axes[i].plot(x, y, label=f'a={a}', linewidth=2)

    axes[i].set_title(f'for ==> b={b}')
    axes[i].set_xlabel('x')
    axes[i].set_ylabel('y')
    axes[i].grid(True, alpha=0.3)
    axes[i].legend()
    axes[i].set_ylim(0, 10)

plt.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt


x = np.linspace(-2, 2, 300)


a_values = [-2, -1, 1, 2]
b_values = [-2, -1, 1, 2]

plt.figure(figsize=(10, 7))


for a in a_values:
    for b in b_values:
        y = b * np.exp(a * x)
        plt.plot(x, y, label=f"a={a}, b={b}")

plt.title(" f(x) = b * e^(a * x) ")
plt.xlabel("x")
plt.ylabel("f(x)")
plt.grid(True)
plt.legend(fontsize=8, ncol=2)
plt.show()